<a href="https://colab.research.google.com/github/santhoshharidev/PRODIGY_ML_01/blob/main/House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
train_df = pd.read_csv('/content/train.csv')
test_df = pd.read_csv('/content/test.csv')

In [ ]:
print(train_df.shape)
print(test_df.shape)

train_df.head()

(1460, 81)
(1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
X_train = train_df[['GrLivArea', 'BedroomAbvGr', 'FullBath']]
y_train = train_df['SalePrice']

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
print("Intercept:", model.intercept_)

for feature, coefficient in zip(X_train.columns, model.coef_):
    print(feature, ":", coefficient)

Intercept: 47509.48218946537
GrLivArea : 110.06172638795802
BedroomAbvGr : -27859.332223528167
FullBath : 29694.68839061572

In [ ]:
X_test = test_df[['GrLivArea', 'BedroomAbvGr', 'FullBath']]

In [ ]:
predictions = model.predict(X_test)

print(predictions[:10])

[120100.81297664 139898.20827909 202611.4145861  199859.8714264
 192059.20430023 205473.01947218 153964.13152262 184561.29145847
 169078.28121928 118559.9488072 ]

In [ ]:
submission = pd.DataFrame({
    'Id': test_df['Id'],
    'PredictedSalePrice': predictions
})

submission.head()

     Id  PredictedSalePrice
0  1461       120100.812977
1  1462       139898.208279
2  1463       202611.414586
3  1464       199859.871426
4  1465       192059.204300

In [ ]:
submission.to_csv('predictions.csv', index=False)

print("Prediction file created successfully!")

Prediction file created successfully!